Small improvements to lxp script

diff --git a/home/dot_local/bin/cern_ws/executable_lxp b/home/dot_local/bin/cern_ws/executable_lxp
--- a/home/dot_local/bin/cern_ws/executable_lxp
+++ b/home/dot_local/bin/cern_ws/executable_lxp
@@ -14,10 +14,13 @@ do_atlasgw_proxy=false
 do_vnc_proxy=false
 vnc_port=5907
 
+do_bkg=false
+
 do_kerb_only=false
 
 do_cm_start_only=false
 do_cm_exit_only=false
+do_cm_status_only=false
 
 #------------------------------------------
 # Parse cmd line arguments
@@ -42,6 +45,10 @@ while [[ $# -gt 0 ]]; do
             vnc_port=$((5900 + $offset))
             shift
             ;;
+        -b|--background)
+            do_bkg=true
+            shift
+            ;;
         -k|--kerb)
             do_kerb_only=true
             shift
@@ -54,8 +61,12 @@ while [[ $# -gt 0 ]]; do
             do_cm_exit_only=true
             shift
             ;;
+        -s|--cm-status|--cms)
+            do_cm_status_only=true
+            shift
+            ;;
         -h|--help)
-            echo "Usage: lxp [-u|--user USER] [-p|--p1-proxy] [-v|--vnc[=OFFSET]] [-k|--kerb] [-c|--cm] [-e|--cm-exit] [lxhost]"
+            echo "Usage: lxp [-u|--user USER] [-p|--p1-proxy] [-v|--vnc[=OFFSET]] [-b|--background] [-k|--kerb] [-c|--cm] [-e|--cm-exit] [-s|--cm-status] [lxhost]"
             echo
             echo "LXPlus ssh connection manager."
             echo "A persistent background ControlMaster (CM) session will be initialized for each ssh target."
@@ -64,9 +75,11 @@ while [[ $# -gt 0 ]]; do
             echo "  -u, --user USER         Use the specified USER instead of \$CERN_USERNAME (or \$USER)."
             echo "  -p, --p1-proxy          Pipe proxy to P1 (atlasgw.cern.ch) using port 3128."
             echo "  -v, --vnc, --vnc=OFFSET Set VNC proxy on port 5900+OFFSET, using OFFSET=7 by default if not provided."
+            echo "  -b, --background        Keep the ssh connection in the background without a shell (e.g. for port forwarding); same as using 'ssh -fN'."
             echo "  -k, --kerb              Open Kerberos token only using k5start, with the keytab located at \$HOME/.keytab."
             echo "  -c, --cm                Open SSH ControlMaster background session only."
             echo "  -e, --cm-exit, --cme    Exit SSH ControlMaster background session only."
+            echo "  -s, --cm-status, --cms  Show all valid SSH ControlMaster sessions only."
             echo "  -h, --help              Show this help message and exit."
             echo
             echo "The final argument is used to get the LXPlus host:"
@@ -106,8 +119,8 @@ if [[ -n "$lxhost_arg" && "$do_kerb_only" = true ]]; then
     exit 1
 fi
 
-if [[ ("$do_kerb_only" = true || "$do_cm_start_only" = true || "$do_cm_exit_only" = true) && ("$do_atlasgw_proxy" = true || "$do_vnc_proxy" = true) ]]; then
-    echo "lxp: cannot use both --kerb/--cm/--cm-exit and --p1-proxy/--vnc simultaneously" >&2
+if [[ ("$do_kerb_only" = true || "$do_cm_start_only" = true || "$do_cm_exit_only" = true || "$do_cm_status_only" = true) && ("$do_atlasgw_proxy" = true || "$do_vnc_proxy" = true) ]]; then
+    echo "lxp: cannot use both --kerb/--cm/--cm-exit/--cm-status and --p1-proxy/--vnc simultaneously" >&2
     exit 1
 fi
 
@@ -149,7 +162,7 @@ target="${user}@${lxhost}.cern.ch"
 
 
 #------------------------------------------
-# Get ControlMaster path
+# Get ControlMaster directory path
 #------------------------------------------
 if [[ "$(uname)" == "Linux" ]]; then
     CM_PATH="/run/user/$(id -u)"
@@ -159,17 +172,46 @@ fi
 
 
 #------------------------------------------
+# Get all open ControlMaster sessions
+#------------------------------------------
+# Avoid literal * if no files match
+shopt -s nullglob
+cms=()
+for f in "$CM_PATH"/*; do
+    if [[ $(basename "$f") =~ ^([^:@]+@[^:@]+):[0-9]+$ ]]; then
+        cms+=("${BASH_REMATCH[1]}")
+    fi
+done
+
+
+#------------------------------------------
+# Show list of open ControlMaster sessions
+#------------------------------------------
+if [[ "$do_cm_status_only" = true ]]; then
+    if [[ "${#cms[@]}" == 0 ]]; then
+        echo "No open SSH ControlMaster sessions"
+    else
+        echo "Open SSH ControlMaster sessions:"
+        printf -- '- %s\n' "${cms[@]}"
+    fi
+    exit 0
+fi
+
+
+#------------------------------------------
 # ControlMaster session exit
 #------------------------------------------
 # First check if the CM link exists
 if [[ "$do_cm_exit_only" = true ]]; then
-    if [[ -e "$CM_PATH/$target:22" ]]; then
-        ssh -O exit "$target"
-        exit 0
-    else
-        echo "lxp: no ssh ControlMaster session for $target" >&2
-        exit 1
-    fi
+    for cm_session in "${cms[@]}"; do
+        if [[ "$cm_session" == "$target" ]]; then
+            ssh -O exit "$target"
+            exit 0
+        fi
+    done
+
+    echo "lxp: no ssh ControlMaster session for $target" >&2
+    exit 1
 fi
 
 
@@ -198,9 +240,19 @@ if [[ "$do_vnc_proxy" = true ]]; then
     args+=("-L${vnc_port}:localhost:${vnc_port}")
 fi
 
+if [[ "$do_bkg" = true ]]; then
+    # -x to disable X11 forwarding
+    # -f to fork the connection to the background
+    # -N to not spawn a shell in the remote host
+    args+=("-xfN")
+else
+    # -Y to enable trusted X11 forwarding
+    args+=("-Y")
+fi
+
 args+=("$target")
 
 # Initialize ssh connection
-ssh -Y "${args[@]}"
+ssh "${args[@]}"
 
 exit 0
